eschool/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls import url
from django.views.static import serve

from . import settings


urlpatterns = [
    path('', include('home.urls')),
    path('admin/', admin.site.urls),
    path('school/', include('schoolregister.urls')),
    path('files/', include('fileshare.urls')),
]

if settings.DEBUG:
    urlpatterns += [
        url(r'^media/(?P<path>.*)$', serve, {
            'document_root': settings.MEDIA_ROOT,
        }),
    ]

fileshare/urls.py
from django.urls import path, include

from . import views


app_name = 'fileshare'
urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('<int:pk>/', include([
        path('delete/', views.FileDeleteView.as_view(), name='delete'),
        path('download/', views.FileDownloadView.as_view(), name='download'),
        path('share/', views.FileShareView.as_view(), name='share'),
        path('show/', views.FileShowView.as_view(), name='show'),
    ]))
]

home/urls.py
from django.urls import path, re_path, include
from django.contrib.auth import views as auth_views
from django.views.static import serve

from eschool import settings
from . import views

app_name = 'home'
urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    re_path(r'^login/$', auth_views.login, {'template_name': 'home/login.html'}, name='login'),
    re_path(r'^logout/$', auth_views.logout, {'next_page': '/'}, name='logout'),
    path('<int:pk>/profile/', include([
        path('', views.ProfileView.as_view(), name='profile'),
    ])),
    path('contact/', views.ContactView.as_view(), name='contact'),
]

schoolregister/urls.py
from django.urls import path, include

from . import views


app_name = "schoolregister"
urlpatterns = [
    path("", views.IndexView.as_view(), name="index"),
    # ex: /school/lesson/
    path(
        "lesson/",
        include(
            [
                path("", views.LessonPortalView.as_view(), name="lesson_portal"),
                # ex: /school/lesson/1/
                path(
                    "<int:lesson_pk>/",
                    views.LessonView.as_view(),
                    name="lesson_details",
                ),
            ]
        ),
    ),
    # ex: /school/taught/1/
    path("taught/<int:taught_pk>/", views.TaughtView.as_view(), name="taught_details"),
    # ex: /school/my-classes
    path("groups/", views.GroupsList.as_view(), name="groups"),
    # ex: /school/group/1/
    path(
        "group/<str:abbrev>/",
        include(
            [
                path("", views.GroupView.as_view(), name="group_details"),
                # ex: /school/group/1/give_grades/
                path(
                    "give_grades/",
                    views.GiveGroupGradesView.as_view(),
                    name="give_group_grades",
                ),
            ]
        ),
    ),
    # ex: /school/student/1/
    path(
        "student/<int:student_pk>/",
        include(
            [
                path("", views.StudentView.as_view(), name="student_details"),
                # ex: /school/student/1/grades/
                path("grades/", views.GradesView.as_view(), name="grades"),
                # ex: /school/student/1/add-grade/
                path("add-grade/", views.GradeAddView.as_view(), name="grade_add"),
                # ex: /school/student/1/notes/
                path("notes", views.NotesView.as_view(), name="notes"),
                # ex: /school/student/1/add-note/
                path("add-note/", views.NoteAddView.as_view(), name="note_add"),
                # ex: /school/student/1/grade/1/
                path(
                    "grade/<int:grade_pk>/",
                    include(
                        [
                            path("", views.GradeView.as_view(), name="grade_details"),
                            # ex: /school/student/1/grade/1/edit
                            path(
                                "edit/",
                                views.GradeEditView.as_view(),
                                name="grade_edit",
                            ),
                            # ex: /school/student/1/grade/1/delete
                            path(
                                "delete/",
                                views.GradeDeleteView.as_view(),
                                name="grade_delete",
                            ),
                        ]
                    ),
                ),
                # ex: /school/student/1/note/1
                path(
                    "note/<int:note_pk>/",
                    include(
                        [
                            path("", views.NoteView.as_view(), name="note_details"),
                            # ex: /school/student/1/note/1/edit
                            path(
                                "edit/", views.NoteEditView.as_view(), name="note_edit"
                            ),
                            # ex: /school/student/1/note/1/delete
                            path(
                                "delete/",
                                views.NoteDeleteView.as_view(),
                                name="note_delete",
                            ),
                        ]
                    ),
                ),
            ]
        ),
    ),
    # ex: /school/teacher/1/
    path(
        "teacher/<int:teacher_pk>/", views.TeacherView.as_view(), name="teacher_details"
    ),
]

home/models.py
# -*- coding: utf-8 -*-
from django.contrib.auth.models import AbstractUser
from django.db import models


class User(AbstractUser):

    class Meta:
        ordering = ['last_name']

    is_student = models.BooleanField('student status', default=False)
    is_teacher = models.BooleanField('teacher status', default=False)
    is_writer = models.BooleanField('teacher status', default=False)

    def __str__(self):
        return self.full_name()

    def __repr__(self):
        return self.full_name()

    def full_name(self):
        return ' '.join([self.first_name, self.last_name])

    def get_last_actions(self):
        """Gets last actions interesting for user.
        If user is student last actions are false-presences, grades and notes.
        If user is teacher last actions are false-presences, grades and notes
            of students of class that user is supervising, or nothing if user
            is not supervisor of any class."""
        if self.is_student:
            return None
        elif self.is_teacher:
            return None

home/views.py
# -*- coding: utf-8 -*-
from django.http import HttpResponseRedirect
from django.shortcuts import get_object_or_404, render
from django.urls import reverse
from django.views import View
from django.contrib.auth.decorators import login_required
from django.utils.decorators import method_decorator

from .models import User


class ContactView(View):
    template_name = 'home/contact.html'

    def get(self, request, *args, **kwargs):
        return render(request, self.template_name, {})


class IndexView(View):
    template_name = 'home/index.html'

    def get(self, request):
        context = {'welcome': "Yo mon! You're at our school homepage!"}
        return render(request, self.template_name, context)


@method_decorator(login_required, name='dispatch')
class ProfileView(View):
    template_name = 'home/profile.html'

    def get(self, request, *args, **kwargs):
        user = get_object_or_404(User, id=kwargs['pk'])
        if user.is_teacher:
            return HttpResponseRedirect(reverse(
                'schoolregister:teacher_details',
                kwargs={'teacher_pk': user.teacher.id}
            ))
        if user.is_student:
            return HttpResponseRedirect(reverse(
                'schoolregister:student_details',
                kwargs={'student_pk': user.student.id}
            ))
        viewer = request.user
        context = {
            'user': user,
            'viewer': viewer
        }
        return render(request, self.template_name, context)

templates/home/__base.html
{% load staticfiles %}
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<!--
Design by TEMPLATED
http://templated.co
Released for free under the Creative Commons Attribution License

Name       : Unwritten
Description: A two-column, fixed-width design with a bright color scheme.
Version    : 1.0
Released   : 20120710
-->
<html xmlns="http://www.w3.org/1999/xhtml">
	<head>
		<meta http-equiv="content-type" content="text/html; charset=utf-8" />
		<meta name="description" content="" />
		<meta name="keywords" content="" />
		<title>eSchool:{% block title %}{% endblock %}</title>
		<link href="http://fonts.googleapis.com/css?family=Kreon" rel="stylesheet" type="text/css" />
		<link href="http://fonts.googleapis.com/css?family=Satisfy" rel="stylesheet" type="text/css" />
		<link rel="stylesheet" type="text/css" href="{% static 'home/style.css' %}" />
	</head>
	<body>
		<div id="wrapper">
			{% include 'home/_header.html' %}
			{% include 'home/_menu.html' %}
			<!--
			<div id="splash">
				<img src="images/splash.jpg" width="1100" height="250" alt="" />
			</div>
		-->
			<section>
				<div id="content">
					<div class="post">
						{% block content %}{% endblock %}
					</div>
					<div id="col1" class="post">
						{% block left-column %}{% endblock %}
					</div>
					<div id="col2" class="post">
						{% block right-column %}{% endblock %}
					</div>
					<br class="clearfix" />
				</div>
			</section>
			<aside>
				{% include 'home/_base_aside.html' %}
			</aside>
				<br class="clearfix" />
		</div>
		<footer>
			&copy; Untitled | Design by <a href="http://templated.co" rel="nofollow">TEMPLATED</a> | Converted to HTML5 by Norbiox | Images by <a href="http://fotogrph.com/">Fotogrph</a>
		</footer>
	</body>
</html>

templates/home/_base_aside.html
{% block aside %}
<div class="post">
  <h3>News feeed</h3>
  <ul>
    <li>News 1</li>
    <li>News 2</li>
  </ul>
</div>

<div class="post">
  <h3>Quote of the day</h3>
  <p>Never give up on what you really want to do. The person with big dreams is more powerful than one with all the facts.</p>
</div>
{% endblock %}

templates/home/_header.html
{% block header %}
<header>
    <div id="logo">
        <h1><a href="{% url 'home:index' %}">eSchool</a></h1>
    </div>
    <div id="user-panel">
        {% if user.is_authenticated %}
        <p>welcome, {{ user.first_name }}</p>
        <a class="button" href="{% url 'home:profile' user.id %}">My Profile</a>
        <a class="button" href="{% url 'home:logout' %}">Logout</a>
        {% else %}
        <a class="button" href="{% url 'home:login' %}">Login</a>
        {% endif %}
        <br class="clearfix" />
    </div>
</header>
{% endblock %}

templates/home/_menu.html
{% block nav %}
<nav>
    <ul>
        <li><a href="{% url 'home:index' %}">Home</a></li>
        <li><a href="#">News</a></li>
        <li><a href="#">About School</a></li>
        <li><a href="{% url 'home:contact' %}">Contact</li>
        {% if user.is_authenticated %}
          <li><a href="{% url 'schoolregister:index' %}">SchoolRegister</a></li>
          <li><a href="{% url 'fileshare:index' %}">Files Storage</a></li>
        {% endif %}
    </ul>
    <br class="clearfix" />
</nav>
{% endblock %}

templates/home/contact.html
{% extends 'home/__base.html' %}

{% block title %}Contacts{% endblock %}

{% block content %}
  <p>programmer</p>
  {% include 'admin/_my_card.html' %}
{% endblock %}

templates/home/index.html
{% extends 'home/__base.html' %}

{% block title %}Welcome{% endblock %}

{% block content %}
{% if user.is_authenticated %}
<h2>Hello, {{ user.first_name }}</h2>
{% else %}
<h2>Welcome</h2>
{% endif %}
<p>
    You're on eSchool homepage.
</p>
{% endblock %}

templates/home/login.html
{% extends 'home/__base.html' %}

{% block title %}Login{% endblock %}

{% block content %}
  <h2>Login</h2>
  <p>You must login as teacher or student to see that page.</p>
  <form action="{% url 'home:login' %}" method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Login</button>
  </form>
{% endblock %}

templates/home/profile.html
{% extends 'home/__base.html' %}

{% block title %}{{ user.full_name }}:Profile{% endblock %}

{% block content %}
  <h2>{{ user.full_name }}</h2>
  <p>{{ user.email }}</p>
{% endblock %}