eschool/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls import url
from django.views.static import serve

from . import settings


urlpatterns = [
    path('', include('home.urls')),
    path('admin/', admin.site.urls),
    path('school/', include('schoolregister.urls')),
    path('files/', include('fileshare.urls')),
]

if settings.DEBUG:
    urlpatterns += [
        url(r'^media/(?P<path>.*)$', serve, {
            'document_root': settings.MEDIA_ROOT,
        }),
    ]

fileshare/urls.py
from django.urls import path, include

from . import views


app_name = 'fileshare'
urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('<int:pk>/', include([
        path('delete/', views.FileDeleteView.as_view(), name='delete'),
        path('download/', views.FileDownloadView.as_view(), name='download'),
        path('share/', views.FileShareView.as_view(), name='share'),
        path('show/', views.FileShowView.as_view(), name='show'),
    ]))
]

home/urls.py
from django.urls import path, re_path, include
from django.contrib.auth import views as auth_views
from django.views.static import serve

from eschool import settings
from . import views

app_name = 'home'
urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    re_path(r'^login/$', auth_views.login, {'template_name': 'home/login.html'}, name='login'),
    re_path(r'^logout/$', auth_views.logout, {'next_page': '/'}, name='logout'),
    path('<int:pk>/profile/', include([
        path('', views.ProfileView.as_view(), name='profile'),
    ])),
    path('contact/', views.ContactView.as_view(), name='contact'),
]

fileshare/models.py
# -*- coding: utf-8 -*-
import os

from django.db import models

from eschool import settings
from home.models import User


def user_directory_path(instance, filename):
    # file will be uploaded to MEDIA_ROOT/user_<id>/<filename>
    return 'user_{0}/{1}'.format(instance.owner.id, filename)


class File(models.Model):
    class Meta:
        ordering = ['owner', 'uploaded_at']

    owner = models.ForeignKey(User, on_delete=models.CASCADE)
    file = models.FileField(upload_to=user_directory_path)
    uploaded_at = models.DateTimeField(auto_now_add=True)
    description = models.CharField(max_length=200)

    def __str__(self):
        return os.path.basename(self.file.name)

    def __repr__(self):
        return os.path.basename(self.file.name)

    def link(self):
        return '/media/user_{}/{}'.format(self.owner.id, str(self))

    def path(self):
        return settings.MEDIA_ROOT + \
            '/user_{}/{}'.format(self.owner.id, str(self))


class Share(models.Model):
    class Meta:
        ordering = ['shared_to', 'file']

    file = models.ForeignKey(File, on_delete=models.CASCADE)
    shared_to = models.ForeignKey(User, on_delete=models.CASCADE)
    shared_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return str(self.file.owner) + '/' + str(self.file) + \
            ' shared to: ' + str(self.shared_to.full_name())

    def __repr__(self):
        return str(self.file.owner) + '/' + str(self.file) + \
            ' shared to: ' + str(self.shared_to.full_name())

    def owner(self):
        return self.file.owner.full_name()

fileshare/forms.py
from django import forms

from .models import File, User
from schoolregister.models import Group


MAX_UPLOAD_SIZE = "10485760"  # 10Mb


class FileForm(forms.ModelForm):
    class Meta:
        model = File
        exclude = ('owner', 'uploaded_at')

    def clean_file(self):
        content = self.cleaned_data['file']
        if content._size > int(MAX_UPLOAD_SIZE):
            raise forms.ValidationError(
                "Please keep file size under {}. Current file size {}".format(
                    MAX_UPLOAD_SIZE, content._size
                )
            )
        return content


class ShareWithClassForm(forms.Form):

    group = forms.ModelChoiceField(
        queryset=Group.objects.all()
    )

    def clean_group(self):
        group = self.cleaned_data['group']
        return group


class ShareWithUserForm(forms.Form):

    shared_to = forms.ModelChoiceField(
        queryset=User.objects.all()
    )

    def clean_user(self):
        user = self.cleaned_data['user']
        return user

fileshare/views.py
# -*- coding: utf-8 -*-

import os
import mimetypes
from django.http import (
    HttpResponse, HttpResponseRedirect, HttpResponseForbidden
)
from django.shortcuts import get_object_or_404, render
from django.urls import reverse
from django.views import View
from django.contrib.auth.decorators import login_required
from django.utils import timezone
from django.utils.decorators import method_decorator

from .models import File, Share
from .forms import FileForm, ShareWithClassForm, ShareWithUserForm


@method_decorator(login_required, name='dispatch')
class FileDeleteView(View):

    def post(self, request, *args, **kwargs):
        file = get_object_or_404(File, id=kwargs['pk'])
        if file.owner == request.user:
            file.delete()
            if os.path.isfile(file.path()):
                os.remove(file.path())
            return HttpResponseRedirect(reverse('fileshare:index'))
        return HttpResponseForbidden()


@method_decorator(login_required, name='dispatch')
class FileDownloadView(View):

    def get(self, request, *args, **kwargs):
        file = get_object_or_404(File, id=kwargs['pk'])
        with open(file.path(), 'rb') as f:
            data = f.read()
        response = HttpResponse(
            data, content_type=mimetypes.guess_type(file.path())[0]
        )
        response['Content-Disposition'] = "attachment; filename={0}".format(file)
        response['Content-Length'] = os.path.getsize(file.path())
        return response


@method_decorator(login_required, name='dispatch')
class FileShareView(View):
    template_name = 'fileshare/share_file.html'

    def get(self, request, *args, **kwargs):
        file = get_object_or_404(File, id=kwargs['pk'])
        context = {
            'file': file,
            'group_share_form': ShareWithClassForm(),
            'user_share_form': ShareWithUserForm(),
        }
        return render(request, self.template_name, context)

    def post(self, request, *args, **kwargs):
        file = get_object_or_404(File, id=kwargs['pk'])
        if request.user != file.owner:
            return HttpResponseForbidden()
        if 'user-share-submit' in request.POST:
            form = ShareWithUserForm(request.POST)
            if form.is_valid():
                share = Share()
                share.file = file
                share.shared_to = form.cleaned_data['shared_to']
                share.shared_at = timezone.now()
                share.save()
        elif 'group-share-submit' in request.POST:
            form = ShareWithClassForm(request.POST)
            if form.is_valid():
                group = form.cleaned_data['group']
                for student in group.student_set.all():
                    share = Share()
                    share.file = file
                    share.shared_to = student.user
                    share.shared_at = timezone.now()
                    share.save()
        return HttpResponseRedirect(reverse('fileshare:index'))


@method_decorator(login_required, name='dispatch')
class FileShowView(View):

    def get(self, request, *args, **kwargs):
        file = get_object_or_404(File, id=kwargs['pk'])
        user = request.user
        if user == file.owner or file.share_set.filter(shared_to=user):
            return HttpResponseRedirect(file.link())
        return HttpResponseForbidden()


@method_decorator(login_required, name='dispatch')
class IndexView(View):
    template_name = 'fileshare/index.html'
    upload_file_form = FileForm

    def get(self, request, *args, **kwargs):
        context = {
            'user': request.user,
            'upload_file_form': self.upload_file_form(),
        }
        return render(request, self.template_name, context)

    def post(self, request, *args, **kwargs):
        if request.POST['upload_submit']:
            form = FileForm(request.POST, request.FILES)
            if form.is_valid():
                file = form.save(commit=False)
                file.owner = request.user
                file.uploaded_at = timezone.now()
                file.save()
                return HttpResponseRedirect('')
        return HttpResponseRedirect(reverse('fileshare:index'))

templates/fileshare/_file_upload_form.html
{% block file_upload %}
{% load static %}
<h4>Upload file</h4>
<div class='form_div'>
  <form class="file_upload_form" action="" method="post" enctype='multipart/form-data'>
    {% csrf_token %}
    {{ upload_file_form }}
    <input type="submit" name="upload_submit" value="Upload">
  </form>
</div>
<script type="text/javascript" src="{% static 'fileshare/max_file_size.js' %}"></script>
{% endblock %}

templates/fileshare/_files_list.html
{% block files_list %}
  <ul>
    {% for file in my_files %}
      <li>
        <div class="file_list_element">
          <a href="{% url 'fileshare:show' pk=file.id %}">{{ file }}</a>
          <h6>{{ file.description }}</h6>
          <div style="display: inline-flex;">
            <form class="file_inline_form" action="{% url 'fileshare:download' pk=file.id %}" method="get">
              {% csrf_token %}
              <input type="submit" name="download_button" value="Download">
            </form>
            <form class="file_inline_form" action="{% url 'fileshare:share' pk=file.id %}" method="get">
              {% csrf_token %}
              <input type="submit" name="share_button" value="Share">
            </form>
            <form class="file_inline_form" action="{% url 'fileshare:delete' pk=file.id %}" method="post">
              {% csrf_token %}
              <input type="submit" name="delete_button" value="Delete">
            </form>
          </div>
        </div>
      </li>
    {% endfor %}
  </ul>
{% endblock %}

templates/fileshare/_shares_list.html
{% block shares %}
  <ul>
    {% for share in shares %}
      <li>
        <div class="file_list_element">
          <a href="/media/user_{{ share.file.owner.id }}/{{ share.file }}" %}>{{ share.file }}</a>
          <h6>{{ share.file.description }}</h6>
          <a href="{% url 'home:profile' share.file.owner.id %}">
            {{ share.file.owner.full_name }}
          </a>
        </div>
      </li>
    {% endfor %}
  </ul>
{% endblock %}

templates/fileshare/index.html
{% extends 'home/__base.html' %}

{% block title %}Files Storage{% endblock %}

{% block content %}
  {% if user.is_authenticated %}
    <details open><summary>My files</summary>{% include "fileshare/_files_list.html" with my_files=user.file_set.all%}</details>
    <details><summary>Shared with me</summary>{% include "fileshare/_shares_list.html" with shares=user.share_set.all %}</details>
    {% include 'fileshare/_file_upload_form.html' %}
  {% endif %}
{% endblock %}

templates/fileshare/share_file.html
{% extends "home/__base.html" %}

{% block title %}Sharing {{ file }}{% endblock %}

{% block content %}
  <h3>Sharing {{ file }}</h3>
  <div style="display: inline-flex;">
    <div id="share-with-class-form">
      <h4>Share with class</h4>
      <form class="file-share-with-class-form" action="" method="post">
        {% csrf_token %}
        {{ group_share_form }}
        <input type="submit" name="group-share-submit" value="Share">
      </form>
    </div>
    <h2 style="margin: 20px;">OR</h2>
    <div id="share-with-user-form">
      <h4>Share with class</h4>
      <form class="file-share-with-user-form" action="" method="post">
        {% csrf_token %}
        {{ user_share_form }}
        <input type="submit" name="user-share-submit" value="Share">
      </form>
    </div>
  </div>
{% endblock %}