eschool/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls import url
from django.views.static import serve

from . import settings


urlpatterns = [
    path('', include('home.urls')),
    path('admin/', admin.site.urls),
    path('school/', include('schoolregister.urls')),
    path('files/', include('fileshare.urls')),
]

if settings.DEBUG:
    urlpatterns += [
        url(r'^media/(?P<path>.*)$', serve, {
            'document_root': settings.MEDIA_ROOT,
        }),
    ]

fileshare/urls.py
from django.urls import path, include

from . import views


app_name = 'fileshare'
urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('<int:pk>/', include([
        path('delete/', views.FileDeleteView.as_view(), name='delete'),
        path('download/', views.FileDownloadView.as_view(), name='download'),
        path('share/', views.FileShareView.as_view(), name='share'),
        path('show/', views.FileShowView.as_view(), name='show'),
    ]))
]

home/urls.py
from django.urls import path, re_path, include
from django.contrib.auth import views as auth_views
from django.views.static import serve

from eschool import settings
from . import views

app_name = 'home'
urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    re_path(r'^login/$', auth_views.login, {'template_name': 'home/login.html'}, name='login'),
    re_path(r'^logout/$', auth_views.logout, {'next_page': '/'}, name='logout'),
    path('<int:pk>/profile/', include([
        path('', views.ProfileView.as_view(), name='profile'),
    ])),
    path('contact/', views.ContactView.as_view(), name='contact'),
]

schoolregister/urls.py
from django.urls import path, include

from . import views


app_name = "schoolregister"
urlpatterns = [
    path("", views.IndexView.as_view(), name="index"),
    # ex: /school/lesson/
    path(
        "lesson/",
        include(
            [
                path("", views.LessonPortalView.as_view(), name="lesson_portal"),
                # ex: /school/lesson/1/
                path(
                    "<int:lesson_pk>/",
                    views.LessonView.as_view(),
                    name="lesson_details",
                ),
            ]
        ),
    ),
    # ex: /school/taught/1/
    path("taught/<int:taught_pk>/", views.TaughtView.as_view(), name="taught_details"),
    # ex: /school/my-classes
    path("groups/", views.GroupsList.as_view(), name="groups"),
    # ex: /school/group/1/
    path(
        "group/<str:abbrev>/",
        include(
            [
                path("", views.GroupView.as_view(), name="group_details"),
                # ex: /school/group/1/give_grades/
                path(
                    "give_grades/",
                    views.GiveGroupGradesView.as_view(),
                    name="give_group_grades",
                ),
            ]
        ),
    ),
    # ex: /school/student/1/
    path(
        "student/<int:student_pk>/",
        include(
            [
                path("", views.StudentView.as_view(), name="student_details"),
                # ex: /school/student/1/grades/
                path("grades/", views.GradesView.as_view(), name="grades"),
                # ex: /school/student/1/add-grade/
                path("add-grade/", views.GradeAddView.as_view(), name="grade_add"),
                # ex: /school/student/1/notes/
                path("notes", views.NotesView.as_view(), name="notes"),
                # ex: /school/student/1/add-note/
                path("add-note/", views.NoteAddView.as_view(), name="note_add"),
                # ex: /school/student/1/grade/1/
                path(
                    "grade/<int:grade_pk>/",
                    include(
                        [
                            path("", views.GradeView.as_view(), name="grade_details"),
                            # ex: /school/student/1/grade/1/edit
                            path(
                                "edit/",
                                views.GradeEditView.as_view(),
                                name="grade_edit",
                            ),
                            # ex: /school/student/1/grade/1/delete
                            path(
                                "delete/",
                                views.GradeDeleteView.as_view(),
                                name="grade_delete",
                            ),
                        ]
                    ),
                ),
                # ex: /school/student/1/note/1
                path(
                    "note/<int:note_pk>/",
                    include(
                        [
                            path("", views.NoteView.as_view(), name="note_details"),
                            # ex: /school/student/1/note/1/edit
                            path(
                                "edit/", views.NoteEditView.as_view(), name="note_edit"
                            ),
                            # ex: /school/student/1/note/1/delete
                            path(
                                "delete/",
                                views.NoteDeleteView.as_view(),
                                name="note_delete",
                            ),
                        ]
                    ),
                ),
            ]
        ),
    ),
    # ex: /school/teacher/1/
    path(
        "teacher/<int:teacher_pk>/", views.TeacherView.as_view(), name="teacher_details"
    ),
]

schoolregister/models.py
# -*- coding: utf-8 -*-

import logging

from django.core.validators import (
    MinValueValidator,
    MaxValueValidator,
    MaxLengthValidator,
)
from django.urls import reverse
from django.db import models

from home.models import User

logger = logging.getLogger(__name__)


class Subject(models.Model):
    name = models.CharField(max_length=30, primary_key=True)
    abbrev = models.CharField(max_length=7)

    def __str__(self):
        return self.name

    def __repr__(self):
        return self.name


class Teacher(models.Model):
    class Meta:
        ordering = ["user"]

    NONE = ""
    ENGINEER = "Inż."
    MASTER = "Mgr"
    MASTER_ENGINEER = "Mrg Inż"
    TITLES = (
        (NONE, ""),
        (ENGINEER, "Inżynier"),
        (MASTER, "Magister"),
        (MASTER_ENGINEER, "Magister Inżynier"),
    )
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    title = models.CharField(
        max_length=20, choices=TITLES, default=NONE, null=True, blank=True
    )
    specialization = models.ForeignKey(
        Subject, on_delete=models.CASCADE, null=True, blank=True
    )
    birth_date = models.DateField()
    PESEL = models.CharField(max_length=11, unique=True, default="")
    address = models.CharField(max_length=200)
    phone = models.CharField(max_length=17)

    def __str__(self):
        return " ".join([self.user.first_name, self.user.last_name])

    def __repr__(self):
        return " ".join(["Teacher", self.user.first_name, self.user.last_name])

    def full_name(self):
        title = self.title if self.title is not None else ""
        return " ".join([title, self.user.first_name, self.user.last_name])

    def email(self):
        return self.user.email

    def first_name(self):
        return self.user.first_name

    def last_name(self):
        return self.user.last_name

    def active_lesson(self):
        lessons = Lesson.objects.filter(teacher=self)
        active = list(filter(lambda l: l.is_active(), lessons))
        if active:
            return active[0]
        return None

    def is_teaching(self, student):
        common_subjects = student.group.taught_set.filter(teacher=self)
        return common_subjects


class Group(models.Model):
    year = models.IntegerField(
        validators=[MinValueValidator(0), MaxValueValidator(8)]
    )
    letter = models.CharField(max_length=3)
    supervisor = models.OneToOneField(Teacher, on_delete=models.CASCADE)

    @property
    def abbrev(self):
        return str(self.year) + self.letter

    def __str__(self):
        return self.abbrev

    def __repr__(self):
        return " ".join(["Group", self.abbrev])

    def name(self):
        return " ".join(["Group", self.abbrev])

    def number_of_students(self):
        return len(self.student_set.all())

    def students_number(self, student):
        return list(self.student_set.all()).index(student) + 1


class Taught(models.Model):
    subject = models.ForeignKey(Subject, on_delete=models.CASCADE)
    teacher = models.ForeignKey(Teacher, on_delete=models.CASCADE)
    group = models.ForeignKey(Group, on_delete=models.CASCADE)

    def __str__(self):
        return self.group.abbrev + " - " + self.subject.name

    def __repr__(self):
        return " ".join([self.subject, "in", self.group])


class Student(models.Model):
    class Meta:
        ordering = ["user"]

    user = models.OneToOneField(User, on_delete=models.CASCADE)
    group = models.ForeignKey(Group, on_delete=models.CASCADE,
                              blank=True, null=True)
    birth_date = models.DateField()
    PESEL = models.CharField(max_length=11, unique=True)
    address = models.CharField(max_length=200)
    phone = models.CharField(max_length=17)

    def __str__(self):
        return " ".join(
            [self.user.first_name, self.user.last_name, "-", str(self.group)]
        )

    def __repr__(self):
        return " ".join(
            [self.user.first_name, self.user.last_name, "-", str(self.group)]
        )

    def full_name(self):
        return " ".join([self.user.first_name, self.user.last_name])

    def email(self):
        return self.user.email

    def first_name(self):
        return self.user.first_name

    def last_name(self):
        return self.user.last_name

    def number_of(self):
        """Number of student in group list"""
        return self.group.students_number(self)

    def active_lesson(self):
        lessons = Lesson.objects.filter(taught__in=self.group.taught_set.all())
        active = list(filter(lambda l: l.is_active(), lessons))
        if active:
            return active[0]
        return None


class Rate(models.Model):
    value = models.IntegerField(default=0)
    name = models.CharField(max_length=30)

    def __str__(self):
        return str(self.value)

    def __repr__(self):
        return str(self.value)


class Grade(models.Model):
    class Meta:
        ordering = ["datetime"]

    student = models.ForeignKey(Student, on_delete=models.CASCADE)
    subject = models.ForeignKey(Taught, on_delete=models.CASCADE)
    given_by = models.ForeignKey(Teacher, on_delete=models.CASCADE)
    rate = models.ForeignKey(Rate, null=True, blank=True,
                             on_delete=models.CASCADE)
    weight = models.FloatField(default=1.0)
    description = models.CharField(
        max_length=200,
        default="",
        null=True,
        blank=True,
        validators=[MaxLengthValidator(200)],
    )
    datetime = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ["datetime"]
        get_latest_by = ["datetime"]

    def __str__(self):
        return (
            str(self.student) + " " + str(self.student.group) + " : " + str(self.rate)
        )

    def __repr__(self):
        return (
            str(self.student) + " " + str(self.student.group) + " : " + str(self.rate)
        )

    def get_absolute_url(self):
        return reverse("schoolregister:grade_details", kwargs={"pk": self.pk})

    def all_from_this_taught_and_student(self):
        return Grade.objects.filter(student=self.student).filter(subject=self.subject)


class Lesson(models.Model):
    class Meta:
        ordering = ["start_time"]
        get_latest_by = ["start_time"]

    taught = models.ForeignKey(Taught, on_delete=models.CASCADE)
    teacher = models.ForeignKey(Teacher, on_delete=models.CASCADE)
    start_time = models.DateTimeField(auto_now=True)
    end_time = models.DateTimeField(null=True, blank=True)
    topic = models.CharField(max_length=200)

    def __str__(self):
        return " ".join([str(self.taught), str(self.start_time)])

    def __repr__(self):
        return " ".join(["Lesson", str(self.taught), str(self.start_time)])

    def save(self, *args, **kwargs):
        super(Lesson, self).save(*args, **kwargs)
        for student in self.taught.group.student_set.all():
            if Presence.objects.filter(lesson=self).filter(student=student):
                continue
            Presence(lesson=self, student=student, state=True).save()

    def is_active(self):
        """Returns True if lesson has not been closed"""
        if self.start_time and not self.end_time:
            return True
        return False

    def number_of(self):
        """Returns number of lesson from specific subject in specific class."""
        previous_lessons = Lesson.objects.filter(taught=self.taught).filter(
            start_time__lt=self.start_time
        )
        return len(previous_lessons) + 1


class Note(models.Model):
    class Meta:
        ordering = ["-datetime"]

    student = models.ForeignKey(Student, on_delete=models.CASCADE)
    given_by = models.ForeignKey(Teacher, on_delete=models.CASCADE)
    positive = models.BooleanField()
    text = models.CharField(max_length=500)
    datetime = models.DateTimeField(auto_now=True)

    def __str__(self):
        return " ".join([str(self.student), self.text])

    def __repr__(self):
        return " ".join([str(self.student), self.text])


class Presence(models.Model):
    class Meta:
        ordering = ["student"]

    lesson = models.ForeignKey(Lesson, on_delete=models.CASCADE)
    student = models.ForeignKey(Student, on_delete=models.CASCADE)
    state = models.BooleanField(default=False)

    def __str__(self):
        return str(self.state)

schoolregister/forms.py
from django import forms
from django.utils import timezone

from .models import Taught, Rate, Grade, Lesson, Note


class GradeForm(forms.Form):
    def __init__(self, user, student, *args, **kwargs):
        super(GradeForm, self).__init__(*args, **kwargs)
        if "subject" not in kwargs:
            self.fields["Subject"] = forms.ModelChoiceField(
                queryset=Taught.objects.filter(teacher=user.teacher).filter(
                    group=student.group
                )
            )
        self.fields["Rate"] = forms.ModelChoiceField(queryset=Rate.objects.all())
        self.fields["Weight"] = forms.FloatField(
            max_value=2.0, min_value=0.0, initial=1.0
        )
        self.fields["Description"] = forms.CharField(
            widget=forms.Textarea(
                attrs={"cols": "40", "rows": "5", "style": "resize:none;"}
            ),
            max_length=Grade._meta.get_field("description").max_length,
            required=False,
            empty_value="",
        )

    def save(self, user, student, *args, **kwargs):
        grade = Grade(
            student=student,
            given_by=user.teacher,
            datetime=timezone.now(),
            subject=self.cleaned_data["Subject"],
            weight=self.cleaned_data["Weight"],
            rate=self.cleaned_data["Rate"],
            description=self.cleaned_data["Description"],
        )
        grade.save()


class LessonForm(forms.Form):
    def __init__(self, user, *args, **kwargs):
        super(LessonForm, self).__init__(*args, **kwargs)
        if "taught" not in kwargs:
            self.fields["Class&Subject"] = forms.ModelChoiceField(
                queryset=Taught.objects.filter(teacher=user.teacher)
            )
        self.fields["Topic"] = forms.CharField(
            widget=forms.Textarea(
                attrs={"cols": "100", "rows": "2", "style": "resize:none;"}
            ),
            max_length=Grade._meta.get_field("description").max_length,
            required=False,
            empty_value="",
        )

    def save(self, user, *args, **kwargs):
        lesson = Lesson(
            taught=self.cleaned_data["Class&Subject"],
            teacher=user.teacher,
            start_time=timezone.now(),
            topic=self.cleaned_data["Topic"],
        )
        lesson.save()


class NoteForm(forms.Form):
    def __init__(self, user, *args, **kwargs):
        super(NoteForm, self).__init__(*args, **kwargs)
        self.fields["Kind of note"] = forms.ChoiceField(
            choices=[(True, "POSITIVE"), (False, "NEGATIVE")]
        )
        self.fields["Description"] = forms.CharField(
            widget=forms.Textarea(
                attrs={"cols": "40", "rows": "10", "style": "resize:none;"}
            ),
            max_length=Note._meta.get_field("text").max_length,
            required=True,
            empty_value="",
        )

    def save(self, user, student, *args, **kwargs):
        note = Note(
            student=student,
            given_by=user.teacher,
            datetime=timezone.now(),
            positive=self.cleaned_data["Kind of note"],
            text=self.cleaned_data["Description"],
        )
        note.save()

templates/schoolregister/__base.html
{% load staticfiles %}
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<!--
Design by TEMPLATED
http://templated.co
Released for free under the Creative Commons Attribution License

Name       : Unwritten
Description: A two-column, fixed-width design with a bright color scheme.
Version    : 1.0
Released   : 20120710
-->
<html xmlns="http://www.w3.org/1999/xhtml">
	<head>
		<meta http-equiv="content-type" content="text/html; charset=utf-8" />
		<meta name="description" content="" />
		<meta name="keywords" content="" />
		<title>eSchool register:{% block title %}{% endblock %}</title>
		<link href="http://fonts.googleapis.com/css?family=Kreon" rel="stylesheet" type="text/css" />
		<link href="http://fonts.googleapis.com/css?family=Satisfy" rel="stylesheet" type="text/css" />
		<link rel="stylesheet" type="text/css" href="{% static 'home/style.css' %}" />
	</head>
	<body>
		<div id="wrapper">
			{% include 'schoolregister/_header.html' %}
			{% include 'schoolregister/_menu.html' %}
			<!--
			<div id="splash">
				<img src="images/splash.jpg" width="1100" height="250" alt="" />
			</div>
		-->
			<section>
				<div id="content">
					<div class="post">
						{% block content %}{% endblock %}
					</div>
					<div id="col1" class="post">
						{% block left-column %}{% endblock %}
					</div>
					<div id="col2" class="post">
						{% block right-column %}{% endblock %}
					</div>
					<br class="clearfix" />
				</div>
			</section>
			<aside>
				{% include 'schoolregister/_base_aside.html' %}
			</aside>
				<br class="clearfix" />
		</div>
		<footer>
			&copy; Untitled | Design by <a href="http://templated.co" rel="nofollow">TEMPLATED</a> | Images by <a href="http://fotogrph.com/">Fotogrph</a>
		</footer>
	</body>
</html>

templates/schoolregister/_base_aside.html
{% block aside %}
<div class="post">
  <h3>Last actions</h3>
  <ul>
    <li>Some grade</li>
    <li>Some note</li>
  </ul>
</div>

<div class="post">
  <h3>Quote of the day</h3>
  <p>Never give up on what you really want to do. The person with big dreams is more powerful than one with all the facts.</p>
</div>
{% endblock %}

templates/schoolregister/_group_minimenu.html
{% block group_minimenu %}

{% if user.is_teacher %}
  <div class="minimenu">
  </div>
{% else %}

{% endif %}

{% endblock %}

templates/schoolregister/_header.html
{% block header %}
<header>

  <div id="logo">
    <h1><a href="{% url 'home:index' %}">eSchool</a></h1>
  </div>

  <div id="user-panel">
    {% if user.is_authenticated %}
      <p>welcome, {{ user.first_name }}</p>

      {% if user.is_teacher %}
        <a class="button" href="{% url 'schoolregister:teacher_details' user.teacher.id %}">My Profile</a>
      {% else %}
        <a class="button" href="{% url 'schoolregister:student_details' user.student.id %}">My Profile</a>
      {% endif %}

      <a class="button" href="{% url 'home:logout' %}">Logout</a>

    {% else %}
      <a class="button" href="{% url 'home:login' %}">Login</a>
    {% endif %}
      <br class="clearfix" />
  </div>
</header>
{% endblock %}

templates/schoolregister/_menu.html
{% block nav %}

{% if user.is_teacher %}
<nav>
    <ul>
        <li><a href="{% url 'home:index' %}">Home</a></li>
        <li><a href="{% url 'schoolregister:index' %}">Main Page</a></li>
        <li><a href="{% url 'schoolregister:groups' %}">Classes</a></li>
        <li><a href="{% url 'schoolregister:lesson_portal' %}">Lessons</a></li>
        <li><a href="{% url 'fileshare:index' %}">Files Storage</a></li>
    </ul>
    <br class="clearfix" />
</nav>
{% else %}
<nav>
    <ul>
        <li><a href="{% url 'home:index' %}">Home</a></li>
        <li><a href="{% url 'schoolregister:index' %}">Main Page</a></li>
        <li><a href="{% url 'schoolregister:grades' student_pk=user.student.id %}">Grades</a></li>
        <li><a href="{% url 'schoolregister:notes' student_pk=user.student.id %}">Notes</a></li>
        <li><a href="{% url 'schoolregister:lesson_portal' %}">Lessons</a></li>
        <li><a href="#">Attendance</a></li>
        <li><a href="{% url 'fileshare:index' %}">Files Storage</a></li>
    </ul>
    <br class="clearfix" />
</nav>
{% endif %}

{% endblock %}

templates/schoolregister/_note_block.html
{% block note_block %}
  <div class="note_container">
    {% if note.positive %}
      <a href="{% url 'schoolregister:note_details' student_pk=note.student.id note_pk=note.id %}">
        <strong><h3 style="color: var(--green-color);">GOOD</h3></strong>
      </a>
    {% else %}
      <a href="{% url 'schoolregister:note_details' student_pk=note.student.id note_pk=note.id %}">
        <strong><h3 style="color: var(--red-color);">BAD</h3></strong>
      </a>
    {% endif %}
    <p>{{ note.text }}</p>
    <a href="{% url 'schoolregister:teacher_details' teacher_pk=note.given_by.id %}">
      <h5>{{ note.given_by.full_name }}</h5>
    </a>
    <h5>{{ note.datetime }}</h5>
  </div>
{% endblock %}

templates/schoolregister/_note_form.html
{% block note_form %}
  <form class="note-form" action="" method="post">
    {% csrf_token %}
    {{ note_form }}
    <input type="submit" name="note-submit" value="Submit"/>
  </form>
{% endblock %}

templates/schoolregister/_student_header.html
{% block student_header %}
  <h2>{{ student.full_name }}</h2>
  <h3>class: <a href="{% url 'schoolregister:group_details' student.group.id %}">{{ student.group }}</a></h3>
  <p>email: <a href="mailto:{{ teacher.email }}">{{ student.email }}</a></p>
{% endblock %}

templates/schoolregister/_subjects.html
{% block _subjects %}
  <ul>
  {% for taught in taughts %}
      <li>
        <a href="{% url 'schoolregister:taught_details' taught.id %}">{{ taught.subject }}</a>
        <p>&nbsp teacher: </p>
        <a href="{% url 'schoolregister:teacher_details' taught.teacher.id %}">{{ taught.teacher }}</a>
      </li>
  {% endfor %}
  </ul>
{% endblock %}

templates/schoolregister/give_group_grades.html
{% extends "schoolregister/__base.html" %}

templates/schoolregister/grades_view.html
{% extends "schoolregister/__base.html" %}

{% block title %}Grades{% endblock %}

{% block content %}

{% include 'schoolregister/_student_header.html' %}

<div class="all_grades_container">
  {% for taught, grade_set in grades.items %}
    <div class="taughts_container">
      <div class="subject-container">
        <h4>{{ taught.subject }}</h4>
      </div>
      <div class="grades_container">
        {% if grade_set|length > 0 %}
          <ul>
            {% for grade in grade_set %}
              <li class="slim-li">
                {% if grade.weight <= 0.8 %}
                <div id="low_weight_grade">
                  <h4><a href="{% url 'schoolregister:grade_details' student_pk=grade.student.id grade_pk=grade.id %}">
                    {{ grade.rate }}
                  </a></h4>
                </div>
                {% elif grade.weight >= 1.2 %}
                <div id="high_weight_grade">
                  <h4><a href="{% url 'schoolregister:grade_details' student_pk=grade.student.id grade_pk=grade.id %}">
                    {{ grade.rate }}
                  </a></h4>
                </div>
                {% else %}
                <div id="medium_weight_grade">
                  <h4><a href="{% url 'schoolregister:grade_details' student_pk=grade.student.id grade_pk=grade.id %}">
                    {{ grade.rate }}
                  </a></h4>
                </div>
                {% endif %}
                <p>{{ grade.description }}</p>
              </li>
            {% endfor %}
          </ul>
        {% else %}
          <p>No grades has been given yet.</p>
        {% endif %}
      </div>
    </div>
  {% endfor %}
</div>


{% endblock %}

templates/schoolregister/groups.html
{% extends 'schoolregister/__base.html' %}

{% block title %}Classes{% endblock %}

{% block content %}

{% if user.is_teacher %}

  {% if myclass %}
    <h3>My class</h3>
    <ul>
      <li>
        <a href="{% url 'schoolregister:group_details' myclass.abbrev %}">{{ myclass.abbrev }}</a>
        {% include 'schoolregister/_group_minimenu.html' %}
      </li>
    </ul>
  {% endif %}

  {% if teaching_in_classes %}
    <h3>I teach in</h3>
      <ul>
      {% for group in teaching_in_classes %}
          <li>
            <a href="{% url 'schoolregister:group_details' group.abbrev %}">{{ group.abbrev }}</a>
            <p>&nbsp supervisor: </p>
            <a href="{% url 'schoolregister:teacher_details' group.supervisor.id %}">{{ group.supervisor }}</a>
            <p>&nbsp subject: </p>
            {% for taught in group.taught_set.all %}
              {% if taught.teacher == user.teacher %}
                <a href="{% url 'schoolregister:taught_details' taught.id %}">{{ taught.subject }}</a>
              {% endif %}
            {% endfor %}
            {% include 'schoolregister/_group_minimenu.html' %}
          </li>
      {% endfor %}
      </ul>
  {% endif %}

  {% if other_classes %}
    <h3>Other classes</h3>
    <ul>
    {% for group in other_classes %}
        <li>
          <a href="{% url 'schoolregister:group_details' group.abbrev %}">{{ group.abbrev }}</a>
          <p>&nbsp supervisor: </p>
          <a href="{% url 'schoolregister:teacher_details' group.supervisor.id %}">{{ group.supervisor }}</a>
        </li>
    {% endfor %}
    </ul>
  {% endif %}

{% elif user.is_student %}

  {% if myclass %}
    <h3>My class</h3>
    <ul>
      <li>
        <a href="{% url 'schoolregister:group_details' myclass.abbrev %}">{{ myclass.abbrev }}</a>
      </li>
    </ul>
  {% endif %}

  {% if other_classes %}
    <h3>Other classes</h3>
    <ul>
    {% for group in other_classes %}
        <li>
          <a href="{% url 'schoolregister:group_details' group.abbrev %}">{{ group.abbrev }}</a>
          <p>&nbsp supervisor: </p>
          <a href="{% url 'schoolregister:teacher_details' group.supervisor.id %}">{{ group.supervisor }}</a>
        </li>
    {% endfor %}
    </ul>
  {% endif %}

{% endif %}

{% endblock %}

templates/schoolregister/note_details.html
{% extends "schoolregister/__base.html" %}

{% block title %}Note {{ note }}{% endblock %}

{% block content %}
  {% include 'schoolregister/_note_block.html' %}
{% endblock %}

templates/schoolregister/notes_view.html
{% extends "schoolregister/__base.html" %}

{% block title %}Notes{% endblock %}

{% block content %}

{% include 'schoolregister/_student_header.html' %}

<div class="notes_container">
  {% for note in notes %}
      {% include 'schoolregister/_note_block.html' %}
  {% endfor %}
</div>


{% endblock %}